source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Rails 8.1 requires Ruby >= 3.2. Use 3.4.x for latest.
ruby '>= 3.2.0'

gem 'rails', '~> 8.1'
gem 'sqlite3', '>= 2.1'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'

gem 'dotenv-rails', groups: [:development, :test]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '~> 3.9'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
